Optimize style
helix-bridge/helix-ui pull request #153
Opened 2022-08-02 10:53 UTC by JayJay1024

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] CI related changes
- [ ] Other... Please describe: optimize style

## Why do we need this pr?
Optimize style

2022-08-05 02:22 UTC, sxlwar requested changes

2022-08-05 02:22 UTC, sxlwar commented on packages/helix/components/transaction/Detail.tsx
> +            copyable={{ icon: <img alt="..." src="/image/copy.svg" /> }}
用shared/widget/Icon，里面有 copy 图标

2022-08-05 02:22 UTC, sxlwar commented on packages/helix/components/transaction/SourceTx.tsx
> +          <Typography.Text
Icon

2022-08-05 02:22 UTC, sxlwar commented on packages/helix/components/transaction/TargetTx.tsx
> +      <Typography.Text
Icon

2022-08-05 02:22 UTC, sxlwar commented on packages/helix/pages/transaction/index.tsx
> +            <Typography.Text copyable={{ icon: <img alt="..." src="/image/copy.svg" /> }} className="custom-copy-icon">
Icon

2022-08-05 02:22 UTC, sxlwar commented on packages/helix/styles/index.scss
> +    .ant-table-tbody > tr > td {
这个不要改，太高了，原样就行

2022-08-05 02:22 UTC, sxlwar commented on packages/shared/components/Navigator.tsx
> +      <span className={`text-base font-normal ${textCls}`}>{t(nav.label)}</span>
多余的span ，加 div 上应该是一样的

2022-08-05 02:22 UTC, sxlwar commented on packages/shared/components/widget/SubscanLink.tsx
> +        copyable={copyable ? { icon: <img alt="..." src="/image/copy.svg" /> } : false}
Icon

2022-08-05 02:22 UTC, sxlwar commented on packages/shared/components/widget/TxStatus.tsx
> +          <Typography.Text copyable={{ icon: <img alt="..." src="/image/copy.svg" /> }} className="custom-copy-icon">
Icon

2022-08-05 02:22 UTC, sxlwar commented on packages/shared/components/Footer.tsx
> -          <GithubOutlined />
这里不要用图片，加到 shared 包的 HelixIcon图标里

2022-08-05 02:22 UTC, sxlwar commented on packages/shared/utils/helper/address.ts
> +
css 控制就行，不用中间省略

2022-08-05 10:16 UTC, JayJay1024 commented on packages/apps/components/AppLayout.tsx
> +          <Drawer
> 格式化后不应该有空格啊

这是「对比之前多一个空格」

2022-08-05 10:20 UTC, JayJay1024 commented on packages/apps/components/form-control/BridgeSelector.tsx
>                    key={index}
> 用 tailwind 在这里应该可以实现 bridger-selector-item 的样式

:active 和颜色不太行

2022-08-05 10:27 UTC, JayJay1024 commented on packages/shared/utils/helper/address.ts
> +
> css 控制就行，不用中间省略

他们说让前6后4

2022-08-05 10:31 UTC, JayJay1024 commented on package.json
>      "lerna": "^4.0.0",
> 装不装这个插件有什么差别？

只检查修改的文件。全部ts,tsx,scss都跑一遍lint太久了

2022-08-08 01:57 UTC, sxlwar commented on packages/shared/utils/helper/address.ts
> +
以前就是前后都有，统一用 css truncate就行，不管前几后几都会面临同样的问题

2022-08-08 02:47 UTC, JayJay1024 commented on packages/shared/components/Navigator.tsx
> +      <span className={`text-base font-normal ${textCls}`}>{t(nav.label)}</span>
加 `text-base font-normal` 或者设置了 `textCls` 的话，放在 div 不合适，一个是这些属性放在 div 本身不太合适，二是可能会出现不居中，为了继续居中 div 需要再加上 居中的 classes

2022-08-09 02:07 UTC, xiaoch05 approved these changes

2022-08-09 02:11 UTC, merged