style: adjust and optimize ui and styles
helix-bridge/helix-ui pull request #179
Opened 2022-08-22 04:28 UTC by JayJay1024

## PR Type

What kind of change does this PR introduce?

- [ ] Other... Please describe:

Adjust and optimize ui and styles.

## Why do we need this pr?

UI and styles optimization.

2022-08-22 04:31 UTC, JayJay1024 commented
- [ ] 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/21007682/185839837-9ee1df28-9333-49dd-a4b2-800fb2e28e06.png">

- [ ] 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/21007682/185839992-179e6083-8d65-4b52-8c8e-549d8cddb0a3.png">

2022-08-23 11:02 UTC, sxlwar requested changes

2022-08-23 11:02 UTC, sxlwar commented on packages/helix/pages/index.tsx
> +    return format(date, 'LLL dd, yyyy') + ' (+UTC)';
DATE_FORMAT = LLL dd, yyyy

2022-08-23 11:02 UTC, sxlwar commented on packages/helix/styles/index.scss
> +
as above

2022-08-24 09:23 UTC, JayJay1024 commented on packages/apps/components/form-control/Direction.tsx
> -        <div className="absolute right-0 top-28 cursor-pointer space-x-2 text-xs">
no need top value anymore

2022-08-24 09:24 UTC, JayJay1024 commented on packages/apps/components/form-control/Direction.tsx
> -        <div className="absolute right-0 top-28 cursor-pointer space-x-2 text-xs">
no need top value anymore

2022-08-25 03:52 UTC, sxlwar requested changes

2022-08-25 03:52 UTC, sxlwar commented on packages/apps/components/form-control/Direction.tsx
> -        <div className="absolute right-0 top-28 cursor-pointer space-x-2 text-xs">
第一，结构变化，第二需要增加额外的自定义class，第三得改子组件接口。
改 top 值 只要改一处，简单点不好么？

2022-08-25 04:19 UTC, JayJay1024 commented on packages/apps/components/form-control/Direction.tsx
> -        <div className="absolute right-0 top-28 cursor-pointer space-x-2 text-xs">
好了

2022-08-25 10:29 UTC, sxlwar approved these changes

2022-08-25 10:30 UTC, merged